# Generated by Django 4.2.6 on 2023-10-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_course_preview_alter_lesson_preview_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='lms.course', verbose_name='курс'),
        ),
    ]
